### ISSUE TITLE
[アクションが必要] AWS Lambda における Go 1.x ランタイムのサポート終了 | [Action Required] AWS Lambda end of support for the Go 1.x runtime [AWS Account: 334832660826] [AP-NORTHEAST-1]

### ISSUE THREAD

**Issue by takoikatakotako** [takoikatakotako/charalarm-backend#135]
English follows Japanese | 英語のメッセージは日本語の後にございます

いつもお世話になっております。

お客様の AWS アカウントに現在 Go 1.x ランタイムを使用する 1 つ以上の Lambda 関数があることを確認しましたので、ご連絡いたします。

Amazon Linux AMI のメンテナンスサポートが 2023 年 12 月 31 日に終了するのに合わせて、AWS Lambda での Go 1.x ランタイムのサポートを終了します [1]。Lambda は、provided.al2 ランタイムを使用して Go プログラミング言語を引き続きサポートします。provided.al2 ランタイムを使用すると、AWS Graviton2 プロセッサのサポートや、より小さなデプロイパッケージとより高速な関数呼び出しパスによる効率的な実装など、go1.x ランタイムに比べていくつかの利点があります。詳細については、ブログ記事 [2] を参照してください。

Lambda ランタイムサポートポリシー [3] で説明されているように、Lambda での言語ランタイムのサポートの終了は 2 段階で行われます。2023 年 12 月 31 日以降、Lambda は Lambda 関数で使用される Go 1.x ランタイムにセキュリティパッチやその他アップグレードを適用しなくなり、Go 1.x を使用する関数は、テクニカルサポートの対象外となります。さらに、Go 1.x ランタイムを使用する新しい Lambda 関数を作成できなくなります。2024 年 1 月 30 日以降、Go 1.x ランタイムを使用して既存の関数を更新することができなくなります。

2023 年 12 月 31 日までに、既存の Go 1.x 関数を provided.al2 ランタイムにアップグレードすることをお勧めします。

サポートの終了は機能の実行には影響しません。関数は引き続き実行されます。しかしながら、AWS Lambda チームによるメンテナンスやパッチ適用がされない、サポートされていないランタイムで実行されることとなります。

この通知は、$LATEST 関数バージョンの Go 1.x ランタイムを使用する関数に対して生成されました。影響を受けるリソースのリストは、Personal Health Dashboard の [影響を受けるリソース] タブからご確認いただけます。次のコマンドは、AWS CLI [4] を使用して、Go 1.x を使用している特定のリージョンの公開されている関数バージョンを含むすべての関数を一覧表示する方法を示しています。お客様のアカウント内のこのような関数すべてを確認するには、リージョンごとに次のコマンドを繰り返してください。

aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='go1.x'].FunctionArn"

Lambda の請求には、go1.x ランタイムと provided.al2 ランタイムとの間に違いがあります。go1.x ランタイムでは、Lambda は関数の初期化 (コールドスタート) に費やされた時間を請求しませんが、provided.al2 ランタイムでは、Lambda は請求される関数実行時間に関数の初期化時間を含めます。Go 関数は通常非常に迅速に初期化され、Lambda は複数の関数呼び出しに関数実行環境を再利用することで初期化の回数を減らすため、実際には Lambda 請求額の違いはごくわずかです。

ご不明な点がある場合や、さらにサポートが必要な場合は、AWS サポート [5] にお問い合わせください。

[1] https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/
[2] https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/
[3] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
[4] https://aws.amazon.com/cli/
[5] https://aws.amazon.com/support

**Comment by d-yuji** [comment]
参考
https://gs2.hatenablog.com/entry/2023/08/26/202637

**Comment by takoikatakotako** [comment]
ありがとう！！！
なるほど、カスタムランタイム使う必要あるのか。
バイナリになるからまぁいいとしても、カスタムランタイム初めてだから少し緊張するなー。
ありがとう、やってみるね！

**Comment by takoikatakotako** [comment]
```
aws lambda list-functions --function-version ALL --region ap-northeast-1 --output text --query "Functions[?Runtime=='go1.x'].FunctionArn" --profile sandbox
```
